apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Values.namespace }}"
  name: issue-sync
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    service-group: "{{ .Values.labels.service_group }}"

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ default "issue-sync" .Values.deployment.name }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "issue-sync" .Values.deployment.name }}"
    service-group: backend
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ int .Values.scaling.replicas }}
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ default "issue-sync" .Values.deployment.name }}"
        service-group: backend
        log-style: uwsgi
        env: "{{ .Values.namespace }}"
      namespace: "{{ .Values.namespace }}"
      # annotations:
      #   prometheus.io/scrape: 'true'
    spec:
      serviceAccount: issue-sync

      containers:
      - name: "{{ default "issue-sync" .Values.deployment.name }}"
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: LOGLEVEL
          value: "{{ default "40" .Values.loglevel }}"
        - name: VAULT_ENABLED
          value: "1"
        - name: VAULT_HOST
          value: "{{ .Values.vault.host }}"
        - name: VAULT_PORT
          value: "{{ .Values.vault.port }}"
        - name: VAULT_CERT
          value: /etc/vault-certificate/vaulttls.cert.pem
        - name: VAULT_ROLE
          value: "{{ .Values.vault.role }}-{{ .Values.namespace }}"
        - name: KUBE_TOKEN
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: SQLALCHEMY_DATABASE_HOST
          value: "{{ .Values.database.host }}"
        - name: JIRA_ENDPOINT
          value: "{{ .Values.jira.endpoint }}"
        - name: APPLICATION_ROOT
          value: "{{ .Values.ingress.path }}"
        - name: NAMESPACE
          value: "{{ .Values.namespace }}"

        volumeMounts:
        - name: vault-certificate
          mountPath: /etc/vault-certificate
          readOnly: true
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 30
          httpGet:
            path: "{{ .Values.ingress.path }}/status"
            port: 8000
        readinessProbe:
          periodSeconds: 30
          httpGet:
            path: "{{ .Values.ingress.path }}/status"
            port: 8000

      volumes:
      - name: vault-certificate
        secret:
          secretName: vault-certificate