apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ default "issue-sync" .Values.ingress.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "issue-sync" .Values.deployment.name }}"
    service-group: api
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
    ingress.kubernetes.io/limit-connections: "4"
    ingress.kubernetes.io/limit-rps: "16"
    # ingress.kubernetes.io/auth-url: http://{{ .Values.authenticator.service }}.{{ .Values.namespace }}.svc.cluster.local/auth
    # ingress.kubernetes.io/auth-response-headers: Authorization
    ingress.kubernetes.io/proxy-body-size: 50m
    # ingress.kubernetes.io/rewrite-target: /sync/api
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: "{{ default "/issue-sync" .Values.ingress.path }}"
        backend:
          serviceName: "{{ default "issue-sync" .Values.service.name }}"
          servicePort: 80
